# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-23 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Destination',
            new_name='destination',
        ),
    ]
